#Python setup for shipping server
  - name: install maven
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql
#Install python libraries for mysql connectivity
  - name: install mysql python libraries
    ansible.builtin.pip:
      executable: pip3.9
      name: "{{ item }}"
    loop:
    - cryptography
    - PyMySQL
# App setup
  - name: App setup
    ansible.builtin.import_role:
     name: common-code
     tasks_from: app-setup.yaml
# Install dependencies
  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: move jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  # service setup
  - name: service setup
    ansible.builtin.import_role:
     name: common-code
     tasks_from: service-setup.yaml

  # Load schemas
  
  - name: import shipping data into mysql
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: "{{mysql_host}}"
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

# Daemon reload
  - name: daemon reload
    ansible.builtin.systemd:
      daemon_reload: yes