- name: Ansible playbook to create instances and update r53 records
  hosts: local
  connection: local
  vars:
    servers: 
      - mongodb
      - catalogue
      - redis
      - user
      - cart
      - mysql
      - shipping
      - rabbitmq
      - payment
      - dispatch
      - frontend
    instance_type: t3.micro
    image_id: ami-0220d79f3f480ecf5
    security_group_id: sg-03b441e0ba008f925
    hosted_zone: rscloudservices.icu
    hosted_zone_id: Z0711084A6IKM873A3LI
  tasks:
    # Install dependencies
    - name: Install dependencies
      become: yes
      ansible.builtin.dnf:
        name: 
         - python3
         - python3-pip
        state: present
    # Install dependency libraries to communicate with AWS
    - name: Install dependency_libraries
      become: yes
      ansible.builtin.pip:
        name: 
         - boto3
         - botocore
        executable: pip3
        state: present
    # Create required instances for environment---DEV
    - name: Create instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: "{{ instance_type }}"
        security_groups:
          - "{{ security_group_id }}"
        image_id: "{{ image_id }}"
        tags:
          Name: "{{ item }}"
          Environment: Dev
      loop: "{{ servers }}"
      register: ec2_output
    # Save ec2_output to file
    - name: Save ec2_output to file
      ansible.builtin.copy:
       dest: /home/ec2-user/ec2_output.json
       content: "{{ ec2_output | to_nice_json }}"
    # Print Private IP's
    - name: Print private_ip
      ansible.builtin.debug:
       msg: "Server name is {{ item.instances[0].tags.Name }}. IP address is {{ item.instances[0].private_ip_address }}"
      loop: "{{ ec2_output.results }}"
    # Print Public IP's
    - name: Print public_ip
      ansible.builtin.debug:
       msg: "Server name is {{ item.instances[0].tags.Name }}. IP address is {{ item.instances[0].public_ip_address }}"
      loop: "{{ ec2_output.results }}"
      when: item.item == "frontend"
    # Create r53 records for all servers
    - name: Create r53 records
      amazon.aws.route53:
        state: present
        zone: "{{ hosted_zone }}"
        hosted_zone_id: "{{ hosted_zone_id }}"
        record: "{{ item.instances[0].tags.Name }}.{{ hosted_zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_output.results }}"
    # Create r53 record for frontend
    - name: Create r53 record for frontend
      amazon.aws.route53:
        state: present
        zone: "{{ hosted_zone }}"
        hosted_zone_id: "{{ hosted_zone_id }}"
        record: "{{ hosted_zone }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_output.results }}"
      when: item.item == "frontend"