cart_host: cart-{{ project }}-{{ env }}.rscloudservices.icu
user_host: user-{{ project }}-{{ env }}.rscloudservices.icu
rabbitmq_host: rabbitmq-{{ project }}-{{ env }}.rscloudservices.icu
rabbitmq_user: roboshop
rabbitmq_pass: roboshop123