cart_host: cart-{{ env }}-{{ project }}.rscloudservices.icu
user_host: user-{{ env }}-{{ project }}.rscloudservices.icu
rabbitmq_host: rabbitmq-{{ env }}-{{ project }}.rscloudservices.icu
rabbitmq_user: roboshop
rabbitmq_pass: roboshop123