    - name: Install mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: present
    
    - name: Start and enable mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
  
    - name: Fetch environment-safe MySQL password
      ansible.builtin.set_fact:
        mysql_root_password: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/db/' ~ environment ~ '/mysql_root_password', region='us-east-1', decrypt=True) }}"
 
    - name: Set root password to mysql
      ansible.builtin.shell: mysql_secure_installation --set-root-pass "{{ mysql_root_password }}"