# Call nodejs installation code from common code
 - name: Install nodejs
   ansible.builtin.import_role:
     name: common-code
     tasks_from: nodejs.yaml
#call common code for app setup
 - name: App setup
   ansible.builtin.import_role:
    name: common-code
    tasks_from: app-setup.yaml
# Install dependencies
 - name: Install packages dependencies
   community.general.npm:
    path: /app
###### Setup mongodb connection with Catalogue #######
# Copy mongo-repo
 - name: Copy mongo repo
   ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo
# Install mongodb client 
 - name: Install mongodb client
   ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present
# Load schemas
 - name: Load schemas into mongodb
   ansible.builtin.shell: mongosh --host {{ mongodb_host }} </app/db/master-data.js
# Setup service
 - name: Setup service
   ansible.builtin.import_role:
    name: common-code
    tasks_from: service-setup.yaml
